# Site settings
title: Portfolio Example
email: marb61a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sample Jekyll site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: marb61a
github_username:  marb61a


permalink: /:categories/:title

links: 
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
